config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content

  belongs_to :user
  has_many :images, as: :imageable, dependent: :destroy

  validates :name, :content, presence: true
  validates :name, uniqueness: true

  accepts_nested_attributes_for :images, reject_if: :all_blank,
                                         allow_destroy: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true

  validates :name, presence: true

  has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.includes(:user).all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(
      :name, :content, images_attributes: %i[id name file _destroy]
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'

  def index
    @articles = Article.all.order(created_at: :desc).limit(30)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.haml
%figure{:class => "attachment attachment--#{blob.representable? ? "preview" : "file"} attachment--#{blob.filename.extension}"}
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
  %figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      %span.attachment__name= blob.filename
      %span.attachment__size= number_to_human_size blob.byte_size

app/views/articles/_form.html.haml
= simple_form_for @article do |f|
  = f.input :name
  = f.input :content, as: :rich_text_area, input_html: { style: "height: auto;" }

  %h3 Images
  #images
    = f.simple_fields_for :images do |image|
      = render 'image_fields', f: image
    .links
      = link_to_add_association 'add image', f, :images
  = f.submit 'Save', class: 'btn btn-primary'

app/views/articles/_image_fields.haml
.nested-fields
  .image
    - if f.object.file.attached?
      = image_tag f.object.file.variant(resize_to_limit: [200, 200])
  = f.input :name
  = f.input :file, as: :file
  = link_to_remove_association "remove image", f

app/views/articles/edit.html.haml
.container
  %h1 Editing article

  = render 'form'

  = link_to 'Show', @article
  \|
  = link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles

%table.table
  %thead.thead-dark
    %tr
      %th Name
      %th Content
      %th
      %th
      %th

  %tbody
    - @articles.each do |article|
      %tr
        %td= article.name
        %td= article.content.to_plain_text.truncate(200)
        %td= link_to 'Show', article
        %td= link_to 'Edit', edit_article_path(article)
        %td= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Article', new_article_path, class: %w[btn btn-primary]

app/views/articles/new.html.haml
.container
  %h1 New article
  
  = render 'form'

  = link_to 'Back', articles_path

app/views/articles/show.html.haml
.container
  %p#notice= notice

  %p
    %b Name:
    = @article.name
  %p
    %b Content:
    = @article.content
  %p
    %b User:
    = @article.user.email
  %div
    %b Images
    %ul
      - if @article.images.present?
        - @article.images.each do |image| 
          %li
            = image_tag image.file.variant(resize_to_limit: [200, 200])
            = image.name

  = link_to 'Edit', edit_article_path(@article)
  \|
  = link_to 'Back', articles_path

app/views/home/_article.haml
.card
  - if article.images.present?
    = image_tag article.images.sample.file , class: 'card-img-top', alt: article.name
  .card-body
    %h2.card-title= article.name
    %p.card-text= article.content
  .card-footer
    .row
      .col-12
        %p
          %small.text-muted Created at #{article.created_at.to_formatted_s(:long)}
          %small.text-muted by #{article.user.email}

app/views/home/_carousel.haml
- sample_recent_foods = Array.new.tap do |a|
  - a << OpenStruct.new(name: 'Grilled Meat Burger', description: 'selective focus photography of burger patty, mayonnaise, and French fries served on platter', image: 'food-1.jpeg')
  - a << OpenStruct.new(name: 'Pizza', description: 'cripsy texture with juicy chicken meat... slurp', image: 'food-2.jpeg')
- is_sample = foods.blank?
- foods ||= sample_recent_foods
.carousel.slide.carousel-fade.image-hover{"data-ride" => "carousel", id: "carousel-#{id}"}
  %ol.carousel-indicators
    - foods.each.with_index do |food, index|
      %li{"data-slide-to" => index, "data-target" => "#carousel-#{id}", class: "#{'active' if index.zero?}"}
  .carousel-inner
    - foods.each.with_index do |food, index|
      .carousel-item{ class: "#{'active' if index.zero?}" }
        = image_tag(food.image, class: ['d-block'], width: '800', height: '450', alt: food.name)
        .carousel-caption.d-none.d-md-block.text-shadow
          - if is_sample
            %span.badge.badge-pill.badge-primary Sample
          %h5= food.name
          %p= food.description
          %p recommended image size 800x450
    %a.carousel-control-prev{"data-slide" => "prev", href: "#carousel-#{id}", role: "button"}
      %span.carousel-control-prev-icon{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.carousel-control-next{"data-slide" => "next", href: "#carousel-#{id}", role: "button"}
      %span.carousel-control-next-icon{"aria-hidden" => "true"}
      %span.sr-only Next

app/views/home/index.html.haml
#homepage
  %section#home-panel.jumbotron.text-center.mb-0.py-0.bg-light{style: "background-image: url(#{image_path('table-cover.jpg')}); background-size: cover"}
    .container.vh-100.d-flex
      .row.justify-content-center.align-self-center
        .col-12.shadow.px-3.py-5.mb-5.rounded.text-white
          %h1.h1.jumbotron-heading My Personel Food Blog
          %br/
          %p.lead
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam est voluptas, dolore nam nemo illo ut sapiente vitae commodi magnam provident voluptatum architecto aspernatur animi modi numquam adipisci necessitatibus totam.
  %section.container-fluid
    .row
      .col-sm-6.px-0
        .w-100
          = render 'carousel', id: 'recent', foods: @recent_foods
      .col-sm-6.px-0
        .w-100
          = render 'carousel', id: 'popular', foods: @popular_foods
  %section.container.py-5
    .card-deck
      = render partial: 'article', collection: @articles

app/views/layouts/_login_status.haml
-# - if user_signed_in?
-#   = link_to destroy_user_session_path, method: :delete, data: { confirm: 'Sign out user?' } do
-#     .custom-control.custom-switch
-#       %input{type: 'checkbox', class: 'custom-control-input', id: 'loginStatusSwitch', checked: user_signed_in?, disabled: true}
-#       %label{for: 'loginStatusSwitch', class: 'custom-control-label'}
-#         = current_user.email
-# - else
-#   = link_to new_user_session_path do
-#     .custom-control.custom-switch
-#       %input{type: 'checkbox', class: 'custom-control-input', id: 'loginStatusSwitch', checked: user_signed_in?, disabled: true}
-#       %label{for: 'loginStatusSwitch', class: 'custom-control-label'}

= link_to user_signed_in? ? destroy_user_session_path : new_user_session_path,  method: user_signed_in? ? :delete : nil, data: user_signed_in? ? { confirm: 'Sign out user?' } : nil do
  .custom-control.custom-switch
    %input{type: 'checkbox', class: 'custom-control-input', id: 'loginStatusSwitch', checked: user_signed_in?, disabled: true}
    %label{for: 'loginStatusSwitch', class: "custom-control-label"}
      = user_signed_in? ? current_user.email : 'click to login'

app/views/layouts/_navbar.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.py-3
  %a.navbar-brand{href: '/', data: { toggle: 'tooltip', placement: 'right', title: 'Home'}}
    %span.text-primary.p-3.mb-5.rounded.hover-transition
      %i.fas.fa-home
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto.d-block-inline
      - if user_signed_in?
        %a{href: articles_path}
          %li.nav-item.py-1.my-3.my-lg-1
            %span.text-primary.p-3.mb-5.rounded.hover-transition{data: { toggle: 'tooltip', placement: 'right', title: 'Articles'}}
              %i.fas.fa-newspaper
    %hr/
    .pl-1.ml-2.my-3.my-lg-1
      = render 'layouts/login_status'

app/views/layouts/_notification.haml
- if notice
  %p.alert.alert-info= notice
- if alert  
  %p.alert.alert-danger= alert if alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0, minimum-scale=1'}
    %title Myblog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %main
      %header
        = render 'layouts/navbar'
        = render 'layouts/notification' if flash.present?
      .container.py-5
        = yield
  %footer.container.py-5
    %p
      © 2019 Personel Food Blog

app/views/layouts/home.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0, minimum-scale=1'}
    %title Myblog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %main
      %header
        = render 'layouts/navbar'
        = render 'layouts/notification' if flash.present?
      = yield
  %footer.container.py-5
    %p
      © 2019 Personel Food Blog

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/